apiVersion: apps/v1
kind: Deployment
metadata: { name: banking-service, namespace: devops-demo }
spec:
  replicas: 2
  selector: { matchLabels: { app: banking-service } }
  template:
    metadata: { labels: { app: banking-service } }
    spec:
      containers:
      - name: banking-service
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/banking-microservice:latest
        ports: [{ containerPort: 8080 }]
